// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteProductNotImplementedBody DeleteProductNotImplementedBody delete product not implemented body
//
// swagger:model DeleteProductNotImplementedBody
type DeleteProductNotImplementedBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete product not implemented body
func (m *DeleteProductNotImplementedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete product not implemented body based on context it is used
func (m *DeleteProductNotImplementedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteProductNotImplementedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteProductNotImplementedBody) UnmarshalBinary(b []byte) error {
	var res DeleteProductNotImplementedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
